version: '3'
services:
  db:
    container_name: myDB
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=${DB_PASS}
    ports:
    - 5566:5432
    restart: always
  auth:
    container_name: tct-auth
    image: fusionauth/fusionauth-app
    ports: 
    - 9011:9011
    restart: always
    environment: 
    - DATABASE_URL=jdbc:postgresql://db:5432/postgres
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=${DB_PASS}
